### PR TITLE
Fix closepath "Z" command

### PR DESCRIPTION
**Pull request by ochafik**
The code seemed to assume the closepath command takes an argument, but [it doesn't](https://www.w3.org/TR/SVG2/paths.html#PathDataClosePathCommand).

This fixes `svgShape("M0 0 h1 v1 h-1 Z");` (note that the same shape with a trailing space was working as the space was somehow parsed as a zero argument for Z), along with pretty much all the paths I tried to export from Inkscape.

### CODE REVIEW

**Comment by dinther** [comment]
Thanks for that. Now I have to figure out how to merge your changes. I don't use this git thing much. I try tomorrow

**Comment by earv1** [comment]
Any luck? I also want to use this and I might be able to help out. Are you getting conflicts?

**Comment by ochafik** [comment]
@dinther thanks for looking into it! As far as merging is concerned, unless you have unpublished changes likely to conflict, you should be able to click merge on this issue. Lemme know if I can help!

**Comment by dinther** [comment]
Well, I clicked merge. Everything still works. Thanks for the update.

Still fuzzy on what was considered wrong. Due to the nature of OpenSCAD there are no open shapes which makes "z" irrelevant right? I vaguely recall that the code compares the first and last point and removes one if they are the same.

**Pull request merged**
